-- drop type if exists
DROP TABLE IF EXISTS shopping_list;
DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM (
  'Main', 'Snack', 'Lunch', 'Breakfast'
);

-- drop table if exists

CREATE TABLE shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  price numeric(4,2) NOT NULL,
  date_added date DEFAULT now() NOT NULL,
  checked boolean DEFAULT false NOT NULL,
  category grocery NOT NULL
);
